name: read_clustering
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas =1.1.1
  - matplotlib-base =3.3.1
  - datashader =0.11.1
  - holoviews =1.13.3
  - bokeh =2.2.0
  - scikit-learn =0.23.2
  - hdbscan =0.8.28
  - umap-learn >=0.5.0
  - numba =0.52.0
  - llvmlite =0.35.0
